### ISSUE TITLE
Display size mismatch with fractional scaling

### ISSUE THREAD

**Issue by s417-lama** [pop-os/nvidia-graphics-drivers#149]
**Distribution (run `cat /etc/os-release`):**
 
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
pop-shell:
  Installed: 1.1.0~1652463555~22.04~034fb14
  Candidate: 1.1.0~1652463555~22.04~034fb14
  Version table:
 *** 1.1.0~1652463555~22.04~034fb14 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status
pop-desktop:
  Installed: 1.6.0~1652730043~22.04~983629a
  Candidate: 1.6.0~1652730043~22.04~983629a
  Version table:
 *** 1.6.0~1652730043~22.04~983629a 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
pop-cosmic:
  Installed: 0.1.0~1651251139~22.04~9c251e7
  Candidate: 0.1.0~1651251139~22.04~9c251e7
  Version table:
 *** 0.1.0~1651251139~22.04~9c251e7 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

After recent updates, only a part of workspace is shown on my secondary display (with fractional scaling enabled).

A screenshot of the entire workspace:

![Screenshot from 2022-05-18 13-42-36](https://user-images.githubusercontent.com/26866454/168961142-98ecc0b7-a6dd-4d22-9f96-0de66a6ccb08.png)

It shows that the size of the workspace is properly configured with fractional scaling.

However, at the hardware-level, only the upper left part of the workspace is shown on my display:

![Screenshot from 2022-05-18 13-56-00](https://user-images.githubusercontent.com/26866454/168960823-39548c3c-43fd-49cb-8e2c-c3c2053a2527.png)

(This screenshot was taken by selecting only the human-visible part of the screen)

I'm pretty sure that it was properly working until recent apt upgrade.

**Steps to reproduce (if you know):**

In the display setting:
- disable HiDPI daemon
- enable fractional scaling
- set scale of the secondary display to 1.25 (for example)
    - note that it successfully shows the entire screen with scale = 2.0, but not with any other scales
- selection of "primary display" does not matter

**Expected behavior:**

The whole workspace is shown on the display as before.

**Other Notes:**

Here are my hardware configurations:

Primary display (my laptop)
- HP Zbook create G7
- 3840 x 2160 (4K) at 60 Hz
- NVIDIA GeForce RTX 2070 with Max-Q
- Nvidia driver 510.68.02

Secondary display
- Eizo FlexScan EV2785-UN
- 3840 x 2160 (4K) at 60 Hz

**Comment by s417-lama** [comment]
Thank you for your investigation.

Additionally, while connecting to the secondary display via usb-c, `Xorg` process constantly consumes about 40% CPU time.
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
   3199 root      15  -5   25.8g 147036  82580 R  39.7   0.5 140:33.85 Xorg
```

As this high CPU usage is not observed with a single display, it might be related to this issue.

**Comment by s417-lama** [comment]
Solved with 515.65.01. Thanks!

**Comment by kingfisher64** [comment]
515.65.01 on 22.04 PopOS doesn't work for me. Can you tell me/us @s417-lama how you got it working? Thanks

**Comment by s417-lama** [comment]
I don't think I have done something special. I just upgraded my NVIDIA driver and then the issue disappeared.

I'm using "NVIDIA Graphics" mode, and the Display setting is as follows:

![image](https://user-images.githubusercontent.com/26866454/200219046-516f3a1f-2b0b-4916-8a17-696d84bd4f97.png)

Here is my configuration of GPU:
```
⟩ nvidia-smi -L
GPU 0: NVIDIA GeForce RTX 2070 with Max-Q Design (UUID: GPU-e8029a32-8a3c-5421-2440-1959b767c04f)

⟩ nvidia-smi
Mon Nov  7 12:20:01 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| N/A   62C    P5    26W /  N/A |   3087MiB /  8192MiB |      8%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      3377      G   /usr/lib/xorg/Xorg               1500MiB |
|    0   N/A  N/A      3537      G   /usr/bin/gnome-shell              616MiB |
|    0   N/A  N/A      5412      G   ...eatures=VaapiVideoDecoder      758MiB |
|    0   N/A  N/A   3658945      G   gnome-control-center                2MiB |
+-----------------------------------------------------------------------------+
```

**Comment by kingfisher64** [comment]
@s417-lama thanks for the info. I've tried re-installing the same driver and installing newer and older versions but nothing fixes it. So frustrating as everything else is lovely.

**Comment by zerophilmister** [comment]
@kingfisher64 I am still experiencing this issue as well. I have a fresh install of pop and I've tried 515 and 525. I remember fractional scaling working in the past. I recently decided to give popos a shot again as a daily driver but I unfortunately can't since it doesn't work well with my 4k display.

**Comment by kingfisher64** [comment]
I gave up on linux due to issues like this. Just not viable in a pro
environment.

**Comment by zerophilmister** [comment]
I was able to find a workaround  with font scaling. Here's the command I used: gsettings set org.gnome.desktop.interface text-scaling-factor 1.5
It looks good on my 4k monitor but text and apps on my qhd monitor and hd laptop screen look too big. I mainly use my 4k monitor so it will work. I am just surprised fractional scaling isn't working correctly anymore.

**Comment by neopostmodern** [comment]
Could this be re-opened? It's also not working for me, using 515.65.01

**Comment by s417-lama** [comment]
I noticed that this issue is still happening with the "Hybrid Graphics" mode. With the "NVIDIA Graphics" mode, fractional scaling is working perfectly, but with the "Hybrid Graphics" mode, fractional scaling does not work, even with 100% scaling (only 200% scaling is working).

The current NVIDIA driver version is 535.86.05.

**Comment by OlivierBelan** [comment]
Could this thread be re-opened ? 

Have the same problem on Hybrid Graphics only - any ideas ?

**Comment by OlivierBelan** [comment]
Thanks for the recommendation, in fact what I'm looking for is a hybrid configuration allowing me to choose when to use the NVDIA GPU for certain targeted programs and use the Intel integrated for normal use. At the same time I have to juggle with the fact that I have to use fractional scaling. 

In fact, I'm using wayland at the moment, and this configuration works (fractional + hybrid mode). However, one annoying (and hopefully temporary) problem is that Wayland doesn't (yet) have as much integration as X11 (from what I understand). Notably the problem of integrating applications that are really independent (e.g. blur, windows top bar etc...). One solution is to add flags so that the applications run natively on wayland, but this still seems to be a problem depending on the application and the developer of the app.

So I tried to go back to X11, where most applications are well integrated with the exception of fractional scaling (in hybrid mode), which is really frustrating and ironic.

**Comment by dejvoss** [comment]
Thanks for all the options you listed.
For me the older nvidia drivers works. i m using laptop with  NVIDIA GeForce RTX 3050 Laptop GPU and 4K monitor, fractional scalling with nvidia-driver-565 doesn't work (same issue as above), but with older one is working.
I want to try the waylanad with the newer driver to see if there is diference.
